apiVersion: v1
kind: Secret
metadata:
    name: planka-secrets
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uRk8SZ50NMImN23dLyVeGajTlWyFRrTH//ttT4k=,iv:Ml1EuKCidiL4o3urKNGgtwez9XGp3ApBY2LE/UF4cbw=,tag:04F3cUEYUSfbSwCIZkcDgg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:lIGRhxse5vIFqKCTpH9tHelzpJCM4J/SymCJcpCR8zSBo0jkdAtZza0SOr5wrbAhQcYFFWO2bFcGJSWCNCmi3Dntjeg5MqBho+Ac1VwILkY=,iv:m3swWQcT4jKu4mF4f9LJRMcCpcr2Sdh8N4GPzHmaC/I=,tag:P2/GJDwmUUtSHl494JdtRw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:iJWSkIa/Ho6RMPcT+0BKUC+cTIO3g8pscjhIqBoxXCQdY1U9mr/LZPlQZKeP93GwtMo4jFbFSMJkd160GqKwXA==,iv:i9zDD2Sn0X6XoiGGhT5HC6AwlhcIQ75so1+wZ62bgfc=,tag:Y/aUATXTV+1olWu/wcIEdw==,type:str]
    DEFAULT_ADMIN_EMAIL: ENC[AES256_GCM,data:J8hkkEDgsFKMiIl0KwWhYgIViffqy/3G,iv:MqFWLAm56MUtbKxSExwFVmafuUukVIoZAM5u0w4kgWo=,tag:n+kU30Y4nFny0D3UyveQog==,type:str]
    DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:daHeRTFfewkb+qe08/MhfpPeh6Q=,iv:8ly51wt0wlOj3EEhxBYutI/mTYoGk6sO2MvAmDKYagg=,tag:26PUWBbigvEpo89XybygAA==,type:str]
    DEFAULT_ADMIN_NAME: ENC[AES256_GCM,data:613t7OzB,iv:WPoRv48xNochBF94D62EaoWv1JHKqLEniLlZvm0RXKg=,tag:JX0z6HcJXjutGvqCREvAfw==,type:str]
    DEFAULT_ADMIN_USERNAME: ENC[AES256_GCM,data:GOJ2eJ+r,iv:dhnwq+OUnaFDn/HagiwvIhnhILa/AMDEJiaPAKWD/so=,tag:Wad/Z+Avg6gSsBdHSdNmUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whgt006ah98q4rq3rx0frer4unk7npnt8hdfuqvrsrqdvvldjeus4gwlsy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvblUweC84b3hOaGZrbTU3
            aXdZYkdsNFpZaUhTMFU2LzVCaU0xUDAvQXlvCkxLTGMyQXdWaUlsT2ZKTjJVeXRs
            dmNuT3Z3VDVvdUQrbDlLZGswbGxqNW8KLS0tIERhcnQ1VXp4OU5MRkUzMml0MkZB
            d1EraDErTEd3dEdYc1AyTFhteEtnWGcKV80lRxp80G3KXcvYL20NfH8gCmjXAJse
            e/ijG25xA2NArGfhw4l0f7N9o5JfS9v3nF8AXcH/yJKWTr5J29Relg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T10:22:26Z"
    mac: ENC[AES256_GCM,data:3fS2Z4paqpiTuVzdmClxL9djNaasI1CRHAUBgegvvivpgsvvsuUXqgSl+9P+RCEJckj+ZclKMu6LXBys7jJ0mSVcnHVz6HXE8M2GORngvpvKuqbce/j6h3dIUkKRovok0hdTMuUajEeBstcnWZc6ZdwIsULzLLLfSARKYg8TXS4=,iv:TkIjbV7GvlMWOKvsSCi+6/tyCu6pPt+ZGEFjtdxUGHQ=,tag:qyDoOdFBaQsyX/uAk4f7xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
