apiVersion: v1
kind: Secret
metadata:
    name: planka-secrets
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CXHBWDBeWdDcdw5rPoVhpNPM29cYVPKjpFFELLY=,iv:AfTRyeHUB3xk+BDcJVxSt0yHtF7MQ075dos5DDsUZzc=,tag:3aQzEhlijaupxfNpVrco9g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:StS01KVdbaWAmlRu+h77AZ4fbXRMdpfC5mpj3W+Hrw5i2+FFhapbkVlLL2LpukPIetaTSfIXZ4Hi3W5dzgz1PDsUMxYcbcZWapAx3i4BRCg=,iv:6Jngz1rtNVWLsLmQro7ghIwPr76fcjhGQNxG5ZDWxBg=,tag:mitAQpH/ZJlZxqkN2Hl6/w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:TvhTuMPTGSw4cjJuEP7tcxomjJufvyxWCLKyVm4xkrM3raG04x4e8fhtmkvFRm+LHCVXUAAxhbsMJqA+Ul+yoQ==,iv:fv1VM6Vl565WdGtGsNDQqqQMLQq46vQI7Jo+E5L6PSQ=,tag:qydlj9/4/6xuPzRDsryLIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1whgt006ah98q4rq3rx0frer4unk7npnt8hdfuqvrsrqdvvldjeus4gwlsy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ1J6N09INjFsUmlkWDQ0
            bHRNc0tXa2w3dWtIOXVuS3RPN1d0Q2RWMG13CnpsSjRWQ1Rib215c21CQmd1aS9u
            Z3pSVHB2YkhCczl4TmdlUDROMmZ0encKLS0tIFJQN0VpckVTWFcyc29wYkJGR3M3
            RVhRTGtYUmY0UUExV0pHR2s4V2E5Q0UKqWGKuTgqNXOCu+DV+GHrerZkkCs35J7J
            I2qOAuoxCm1YjencvA0R93imwrPHFztbvUB5LJVNoEuGZN1nG5tcgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T08:13:48Z"
    mac: ENC[AES256_GCM,data:M3GnZ7ACyUHJEn3ErGuKEdV9yF7AmlRjTMxe7hjloPnV7VK07IMkb5wvlV+n/GhMEnvGrWG2WfnIRpJhdN5Q/KeEjLMloiWGLUVWJuYW3psNDudCniGOEj4nFA/ttFYpL/WWK6s42xw2EiNTNFca1GHJOmqGt5FprwJvyBKSQdY=,iv:m2HEZZ+1h1lNpCz79DM9/P4/SyMngmF42F2o3mubGbg=,tag:/M45ew4podNbUURe5bVpSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
