apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-user-data
  labels:
    app.kubernetes.io/name: planka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
