apiVersion: v1
kind: Service
metadata:
  name: planka-service
  labels:
    app.kubernetes.io/name: planka
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 1337
      targetPort: 1337
  selector:
    app.kubernetes.io/name: planka
